export const BOOKING_TIMES = [
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
] as const;

export const HENNA_MODELS = [
  {
    id: "mariage-mandala",
    name: "Mariée mandala",
    tag: "Main complète",
    duration: "2h30",
    pattern: "motif--mandala",
  },
  {
    id: "khaleeji-fingers",
    name: "Khaleeji doigts",
    tag: "Doigts fins",
    duration: "1h",
    pattern: "motif--vine",
  },
  {
    id: "marrakech-floral",
    name: "Florale Marrakech",
    tag: "Fleurs",
    duration: "1h30",
    pattern: "motif--floral",
  },
  {
    id: "bracelet-lune",
    name: "Bracelet lune",
    tag: "Poignet",
    duration: "45 min",
    pattern: "motif--bracelet",
  },
  {
    id: "minimal-dots",
    name: "Pois minimal",
    tag: "Simple",
    duration: "30 min",
    pattern: "motif--dots",
  },
  {
    id: "paume-soleil",
    name: "Paume soleil",
    tag: "Mandala",
    duration: "1h15",
    pattern: "motif--sun",
  },
  {
    id: "arabesque-royale",
    name: "Arabesque royale",
    tag: "Traditionnel",
    duration: "2h",
    pattern: "motif--arabesque",
  },
  {
    id: "pieds-mariage",
    name: "Pieds mariage",
    tag: "Pieds",
    duration: "1h45",
    pattern: "motif--anklet",
  },
  {
    id: "rose-main",
    name: "Rose sur main",
    tag: "Romantique",
    duration: "1h",
    pattern: "motif--rose",
  },
  {
    id: "finesse-doigts",
    name: "Finesse doigts",
    tag: "Fin",
    duration: "40 min",
    pattern: "motif--fine",
  },
  {
    id: "moucharabieh",
    name: "Moucharabieh",
    tag: "Graphique",
    duration: "1h20",
    pattern: "motif--tile",
  },
  {
    id: "full-party",
    name: "Soirée complète",
    tag: "Fête",
    duration: "2h",
    pattern: "motif--party",
  },
] as const;

export type HennaModel = (typeof HENNA_MODELS)[number];
